version: '2'
services:
  web:
    image: tomcat
    ports: 
      - "8081:8081"
    volumes:
      - ./target/*.war:/usr/local/tomcat/webapps/ROOT.war
      #- ./target/DockerExample:/usr/local/tomcat/webapps/ROOT
