version: '2'
services:
  db:
    container_name: db
    image: sahana1212/cricket-app-db
    volumes:
    - "./db:/docker-entrypoint-initdb.d"
    - "my-datavolume:/var/lib/mysql"
  web:
    container_name: web
    image: sahana1212/cricket-app
    ports:
    - 80:8080
    depends_on:
      - db
volumes:
  my-datavolume:
