---
- hosts: all
  become: yes
  #sudo: yes
  become_method: sudo
  vars:
    doc_root: "/var/www/html"
  
  tasks:
    - name: install docker & docker-compose
      raw: sudo apt-get install docker.io -y; sudo apt-get install docker-compose -y;
      
    - name: Checking Docker and Docker-Compose Version
      shell: sudo docker -v; sudo docker-compose -v;
      
    - name: Running docker-compose up
      shell: sudo docker-compose up -d
      
    - name: checking container
      shell: sudo docker ps
